pipeline {
    agent none
    stages {

        stage("Build docker") {
            agent any
            steps {
                    sh 'docker build -f docker/Dockerfile.build ./docker -t local/ijfx-builder'
            }
        }

        stage("Build ImageJFX") {
            agent { docker 'local/ijfx-builder' }
            steps {
                    sh 'bash 0-build.sh'
            }
        }
        stage('Synchronize with repository') {
            agent any
            steps {
                    sh 'bash 1-package.sh'
            }
        }
    }
}

